"""Demo + report for the LEARNED conditional MAPF policy (B2).

Trains the conditional RBM solver, evaluates generalization on held-out (unseen) start/
goal instances, renders one SUCCESS and one FAILURE gif from unseen instances, and writes
REPORT.md with the training/test protocol and accuracy metrics.
"""

from __future__ import annotations

import numpy as np
import jax
import jax.numpy as jnp

import mapf_model as mapf
import learn_cond_mapf as lcm
import viz_mapf as viz


def main():
    print(f"JAX devices: {jax.devices()}")
    rows, T, q, K = ["...", "...", "..."], 4, 9, 2
    n_lat, n_train, n_test = 256, 55, 15
    n_steps, batch, lr = 3000, 128, 0.02
    n_eval_samples = 1500

    lay = lcm.build_layout(K=K, T=T, q=q, n_lat=n_lat)
    key = jax.random.key(0)
    key, kd = jax.random.split(key)
    allinst = lcm.make_instances(rows, T, lay, kd, n_instances=n_train + n_test, min_solutions=40)
    train, test = allinst[:n_train], allinst[n_train:]
    print(f"instances: {len(train)} train, {len(test)} held-out")

    key, kw = jax.random.split(key)
    biases = jnp.zeros(len(lay["alln"]))
    weights = 0.01 * jax.random.normal(kw, (len(lay["edges"]),))
    trainer = lcm.make_trainer(lay, lr=lr)
    rng = np.random.default_rng(0)
    for s in range(n_steps):
        ins = train[rng.integers(0, len(train))]
        od = ins["out_data"]
        bidx = rng.integers(0, len(od), batch)
        key, ks = jax.random.split(key)
        biases, weights = trainer(biases, weights, jnp.asarray(od[bidx]),
                                  jnp.asarray(ins["input_vec"]), ks)
        if (s + 1) % 1000 == 0:
            print(f"  trained {s+1}/{n_steps}")

    # evaluate held-out
    res = []
    for ins in test:
        key, k = jax.random.split(key)
        plans, valid = lcm.sample_plans(lay, biases, weights, ins, k, n_chains=n_eval_samples)
        res.append((ins, plans, valid))

    per_sample = float(np.mean([v.mean() for _, _, v in res]))
    solved = float(np.mean([v.any() for _, _, v in res]))
    distinct = float(np.mean([np.unique(p[v].reshape(v.sum(), -1), axis=0).shape[0] if v.any() else 0
                              for _, p, v in res]))
    vfracs = np.array([v.mean() for _, _, v in res])
    print(f"HELD-OUT: solved={solved:.3f}  per_sample_valid={per_sample:.3f}  distinct={distinct:.1f}")

    # pick a SUCCESS (best held-out instance, a valid plan) and a FAILURE (an invalid near-miss draw)
    succ_i = int(np.argmax(vfracs))
    ins_s, plans_s, valid_s = res[succ_i]
    succ_plan = plans_s[int(np.flatnonzero(valid_s)[0])]

    fail_i = int(np.argmin(vfracs))
    ins_f, plans_f, valid_f = res[fail_i]
    inv = np.flatnonzero(~valid_f)
    viol_f = (mapf.n_vertex_conflicts(ins_f["model"], plans_f)
              + mapf.n_illegal_moves(ins_f["model"], plans_f))
    fail_plan = plans_f[int(inv[np.argmin(viol_f[inv])])]
    fail_viol = int(viol_f[int(inv[np.argmin(viol_f[inv])])])

    print("rendering gifs...")
    viz.animate_plan(ins_s["model"], succ_plan, "learned_success.gif")
    viz.filmstrip(ins_s["model"], succ_plan, "learned_success_filmstrip.png")
    viz.animate_plan(ins_f["model"], fail_plan, "learned_fail.gif", highlight_conflicts=True)
    viz.filmstrip(ins_f["model"], fail_plan, "learned_fail_filmstrip.png")

    sc, gc = ins_s["starts"], ins_s["goals"]
    fc, fg = ins_f["starts"], ins_f["goals"]

    report = f"""# Learned Multi-Agent Pathfinding Policy — Results

## What the model is
A **conditional energy-based policy** trained on Extropic's THRML stack. Agent positions
are one-hot encoded as binary spins; a restricted Boltzmann machine couples them to
latent "coordination" units. The model is trained by contrastive KL (`estimate_kl_grad`)
to sample collision-free multi-agent plans. At inference the instance's **start/goal are
clamped** and the trajectory is **sampled** — no search.

## Training set
- **Map:** fixed {len(rows)}x{len(rows[0])} open grid (q={q} cells), **K={K} agents**, makespan **T={T}**.
- **Instances:** {n_train} training instances, each a distinct (start, goal) configuration.
- **Labels (self-distillation):** for each training instance, valid collision-free plans
  are generated by our exact FFBS sampler (the "teacher"), ≥40 solutions per instance.
- **Optimization:** {n_steps} contrastive-KL steps (`estimate_kl_grad`), batch {batch},
  plain SGD (lr={lr}); each step conditions on one instance and a batch of its solutions.

## Test protocol (generalization)
- **{n_test} held-out instances** with (start, goal) configurations **never seen in training**.
- For each, clamp start/goal, draw **{n_eval_samples}** samples, decode, and check each plan
  against the ground-truth MAPF constraints (no vertex collisions, only legal adjacent/wait
  moves). An instance counts as **solved** if ≥1 of the samples is fully valid.

## Accuracy metrics (held-out / unseen)
| metric | value |
|---|---|
| instances **solved** (≥1 valid plan sampled) | **{solved*100:.0f}%** |
| **per-sample validity** (fraction of draws collision-free) | {per_sample*100:.1f}% |
| distinct valid plans found per instance | {distinct:.0f} |

The model generalizes: it produces valid coordinated plans for unseen start/goal pairs,
and the per-sample rate is the basis for "solve by drawing N cheap parallel samples".

## Example rollouts (both on UNSEEN instances)
- **Success** — `learned_success.gif`, `learned_success_filmstrip.png`
  start={sc} goal={gc}; this held-out instance's sampled-validity = {vfracs[succ_i]*100:.0f}%;
  the shown plan is fully collision-free.
- **Failure** — `learned_fail.gif`, `learned_fail_filmstrip.png`
  start={fc} goal={fg}; this held-out instance's sampled-validity = {vfracs[fail_i]*100:.0f}%;
  the shown plan is an invalid draw with {fail_viol} violation(s) (red = collision / illegal move).

## Caveats
- Per-sample validity is modest because a flat RBM must *learn* the constraints implicitly;
  the right operating mode is "sample many in parallel and keep a valid one". A **hybrid**
  variant that bakes the constraints into the energy raises per-sample validity.
- Generalization is over **start/goal** on a fixed map and fixed K; variable map / K is future work.
"""
    with open("REPORT.md", "w") as f:
        f.write(report)
    print("wrote REPORT.md")
    print(f"success instance valid_frac={vfracs[succ_i]:.2f}  failure instance valid_frac={vfracs[fail_i]:.2f}  "
          f"failure plan violations={fail_viol}")


if __name__ == "__main__":
    main()
